# Generated by Django 4.0.3 on 2022-05-24 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork_advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
                ('length_in_cm', models.FloatField()),
                ('width_in_cm', models.FloatField()),
                ('order_value', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True)),
                ('image_1', models.ImageField(upload_to='Boom/media')),
                ('image_2', models.ImageField(upload_to='Boom/media')),
                ('image_3', models.ImageField(upload_to='Boom/media')),
                ('image_4', models.ImageField(upload_to='Boom/media')),
                ('image_5', models.ImageField(upload_to='Boom/media')),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('national_id_number', models.IntegerField(unique=True)),
                ('birth_date', models.DateField()),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_counter', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('is_artist', models.BooleanField(default=False)),
                ('is_expert', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample_artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('materials', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Boom/media')),
                ('description', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expert_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('fieldofExpertise', models.CharField(max_length=200, null=True)),
                ('backgroundinMonth', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('artwork_advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.artwork_advertisement')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.expert')),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boom.user'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boom.user')),
            ],
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.user'),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('national_id_number', models.IntegerField(unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('free_post_artwork', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('artfield', models.CharField(max_length=200, null=True)),
                ('stylework', models.CharField(max_length=200, null=True)),
                ('Experience_in_month', models.IntegerField(null=True)),
                ('budget', models.IntegerField(default=10000000, null=True)),
                ('last_hipe_month', models.IntegerField(default=0, null=True)),
                ('hipe_count', models.IntegerField(default=2, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boom.user')),
            ],
        ),
    ]
