# Generated by Django 3.2.12 on 2022-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0002_alter_artwork_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='hipe_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
