# Generated by Django 4.0.3 on 2022-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0002_alter_artist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork_advertisement',
            name='Admin_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='Hipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='Hipe_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
