# Generated by Django 3.2.12 on 2022-05-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0003_auto_20220511_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert_comment',
            name='backgroundinMonth',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expert_comment',
            name='fieldofExpertise',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
    ]
