# Generated by Django 3.2.12 on 2022-03-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0003_auto_20220330_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork_advertisement',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.artist'),
        ),
    ]
