# Generated by Django 3.2.12 on 2022-05-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0004_auto_20220517_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork_advertisement',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
