# Generated by Django 4.0.3 on 2022-04-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0006_artist_created_at_artist_free_post_artwork_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='artwork_advertisement',
            name='createAt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='user',
        ),
    ]
