# Generated by Django 4.0.3 on 2022-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0009_alter_artist_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
