# Generated by Django 3.2.12 on 2022-05-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0009_auto_20220530_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork_advertisement',
            name='artist_name',
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
