# Generated by Django 3.2.12 on 2022-05-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0010_auto_20220530_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork_advertisement',
            name='artist_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='examined_price',
            field=models.IntegerField(default=0),
        ),
    ]
