# Generated by Django 4.0.3 on 2022-04-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0012_alter_artist_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='free_post_artwork',
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
    ]
