# Generated by Django 4.0.3 on 2022-04-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0015_artist_user_customer_user_expert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='free_post_artwork',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
