# Generated by Django 4.0.3 on 2022-04-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0017_alter_artist_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.AlterField(
            model_name='artist',
            name='national_id_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
    ]
