# Generated by Django 4.0.3 on 2022-04-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0037_user_is_active_alter_artwork_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
