# Generated by Django 4.0.3 on 2022-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0046_alter_artwork_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork_advertisement',
            name='Admin_perm',
            field=models.BooleanField(default=False),
        ),
    ]
