# Generated by Django 3.2.12 on 2022-04-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0046_alter_artwork_advertisement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork_advertisement',
            name='createAt',
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
