# Generated by Django 3.2.12 on 2022-04-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0047_auto_20220409_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork_advertisement',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
    ]
