# Generated by Django 4.0.3 on 2022-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0048_alter_artist_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
