# Generated by Django 4.0.4 on 2022-04-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0049_alter_artist_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
    ]
