# Generated by Django 3.2.12 on 2022-04-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0049_alter_artwork_advertisement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork_advertisement',
            name='artist',
        ),
    ]
