# Generated by Django 3.2.12 on 2022-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0051_auto_20220409_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
