# Generated by Django 3.2.12 on 2022-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0053_alter_artist_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
