# Generated by Django 3.2.12 on 2022-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0065_auto_20220421_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
    ]
