# Generated by Django 3.2.12 on 2022-05-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0066_auto_20220429_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_counter', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork_advertisement',
            name='order_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.user'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='height_in_cm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sample_artwork',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.user'),
        ),
    ]
