# Generated by Django 4.0.4 on 2022-05-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0066_auto_20220429_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='backgroundinMonth',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expert',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='fieldofExpertise',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sample_artwork',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.user'),
        ),
    ]
