# Generated by Django 3.2.12 on 2022-05-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0067_auto_20220508_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
    ]
