# Generated by Django 3.2.12 on 2022-05-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0069_auto_20220509_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='hipe_count',
            field=models.IntegerField(default=2),
        ),
    ]
