# Generated by Django 3.2.12 on 2022-05-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0070_artist_hipe_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='budget',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
    ]
