# Generated by Django 3.2.12 on 2022-05-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0071_auto_20220510_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='last_hipe_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
