# Generated by Django 3.2.12 on 2022-05-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0072_auto_20220510_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork_advertisement',
            name='Hipe',
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='Boom/media'),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='style',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
