# Generated by Django 3.2.12 on 2022-03-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0004_artwork_advertisement_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork_advertisement',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
