# Generated by Django 4.0.3 on 2022-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0007_remove_artist_created_at_remove_artist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
