# Generated by Django 4.0.3 on 2022-04-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0022_alter_artwork_advertisement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
