# Generated by Django 4.0.3 on 2022-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0023_remove_user_is_staff_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
