# Generated by Django 4.0.3 on 2022-04-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0031_artist_last_login_alter_artwork_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
