# Generated by Django 4.0.3 on 2022-04-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0039_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
