# Generated by Django 3.2.12 on 2022-04-15 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0057_auto_20220414_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork_advertisement',
            name='examined_price',
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Expert_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('artwork_advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.artwork_advertisement')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boom.expert')),
            ],
        ),
    ]
