# Generated by Django 3.2.12 on 2022-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0059_auto_20220417_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sample_artwork',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
