# Generated by Django 3.2.12 on 2022-04-17 16:42

import Boom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0060_auto_20220417_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sample_artwork',
            name='image',
            field=models.ImageField(blank=True, null=True),
        ),
    ]
