# Generated by Django 3.2.12 on 2022-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0062_alter_sample_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
