# Generated by Django 3.2.12 on 2022-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0063_alter_artwork_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=200, null=True),
        ),
    ]
