# Generated by Django 3.2.12 on 2022-04-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boom', '0064_alter_artwork_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork_advertisement',
            name='Admin_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork_advertisement',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], max_length=200, null=True),
        ),
    ]
